# File generated by github.com/posener/goaction. DO NOT EDIT.


FROM golang:1.21.3-alpine3.18
RUN apk add git 

COPY . /home/src
WORKDIR /home/src
RUN go build -o /bin/action ./cmd

ENTRYPOINT [ "/bin/action" ]
