on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions:
  # Goaction needs permissions to update pull requests comments and update contents.
  pull-requests: write
  contents: write
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update action files
        uses: posener/goaction@v1
        with:
          path: cmd/
          image: 1.21.3-alpine3.18
          # Optional: required only for commenting on PRs.
#          github-token: '${{ secrets.GITHUB_TOKEN }}'
      # Optional: now that the script is a Github action, it is possible to run it in the
      # workflow.
#      - name: Example
#        uses: [./](./)