on:
  workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/459292772721/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider'
          service_account: 'github-actions@beta-291013.iam.gserviceaccount.com'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - run: go run cmd/main.go -sheetId 1cNwPjNEHhUdYrCx31G88trjBv7ZZDsoEXBMnfevSNJo -upload